apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.application.name }}-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.application.name }}-cluster-ip
          servicePort: {{ .Values.networking.serviceport }}